const PDFDocument = require('pdfkit');

/**
 * Generate a PDF report from issues array
 * Returns a Buffer
 */
const generateIssuesPDF = (issues, stats) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.rect(0, 0, doc.page.width, 100).fill('#0f172a');
    doc.fillColor('#3b82f6').fontSize(28).font('Helvetica-Bold').text('CivicPulse', 50, 30);
    doc.fillColor('#94a3b8').fontSize(12).font('Helvetica').text('Issue Report — ' + new Date().toLocaleDateString(), 50, 65);

    doc.moveDown(3);
    doc.fillColor('#1e293b');

    // Stats Summary
    if (stats) {
      doc.fillColor('#1e40af').fontSize(16).font('Helvetica-Bold').text('Summary Statistics', 50, doc.y);
      doc.moveDown(0.5);

      const statItems = [
        ['Total Issues', stats.total || 0],
        ['Open', stats.open || 0],
        ['In Progress', stats.inProgress || 0],
        ['Resolved', stats.resolved || 0],
        ['Avg Resolution (hrs)', stats.avgResolutionHours || '—'],
      ];

      statItems.forEach(([label, value]) => {
        doc.fillColor('#374151').fontSize(11).font('Helvetica').text(`${label}:  ${value}`, { continued: false });
      });
      doc.moveDown(1);
    }

    // Table Header
    doc.fillColor('#1e40af').fontSize(14).font('Helvetica-Bold').text('Issue Details', 50, doc.y);
    doc.moveDown(0.5);

    const tableTop = doc.y;
    const colWidths = [180, 80, 60, 80, 90];
    const headers = ['Title', 'Category', 'Priority', 'Status', 'Created'];
    const colX = [50];
    colWidths.forEach((w, i) => colX.push(colX[i] + w));

    // Table header row
    doc.rect(50, tableTop, doc.page.width - 100, 20).fill('#1e3a8a');
    headers.forEach((h, i) => {
      doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold').text(h, colX[i] + 4, tableTop + 5, { width: colWidths[i] - 8 });
    });

    let rowY = tableTop + 22;

    issues.forEach((issue, idx) => {
      if (rowY > doc.page.height - 80) {
        doc.addPage();
        rowY = 50;
      }
      const rowBg = idx % 2 === 0 ? '#f8fafc' : '#ffffff';
      doc.rect(50, rowY, doc.page.width - 100, 18).fill(rowBg);

      const row = [
        (issue.title || '').slice(0, 30),
        (issue.category?.name || '').slice(0, 12),
        issue.priority || '',
        issue.status || '',
        issue.createdAt ? new Date(issue.createdAt).toLocaleDateString() : '',
      ];

      row.forEach((cell, i) => {
        doc.fillColor('#111827').fontSize(9).font('Helvetica').text(cell, colX[i] + 4, rowY + 4, { width: colWidths[i] - 8 });
      });
      rowY += 20;
    });

    // Footer
    doc.moveDown(2);
    doc.fillColor('#6b7280').fontSize(10).text(`Generated by CivicPulse on ${new Date().toLocaleString()}`, { align: 'center' });

    doc.end();
  });
};

module.exports = { generateIssuesPDF };
